name: guard_master
description: A new Flutter project.
publish_to: "none"
version: 1.0.5+2

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.2

  sizer: ^2.0.15
  google_fonts: ^4.0.4
  image_picker: ^0.8.8
  country_picker: ^2.0.21
  flutter_email_sender: ^6.0.2
  url_launcher: ^6.1.14

  permission_handler: ^10.3.0
  unique_identifier: ^0.3.0
  internet_connection_checker_plus: ^1.0.1
  flutter_secure_storage: ^7.0.1

  get: ^4.6.5
  get_storage: ^2.1.1
  get_it: ^7.6.0
  dartz: ^0.10.1

  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.2.5
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1

  badges: ^3.1.2
  pinput: ^3.0.1
  lottie: ^2.4.0
  fluttertoast: ^8.2.2
  # animations: ^2.0.8
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.7
  # persistent_bottom_nav_bar: ^5.0.2
  cached_network_image: ^3.2.3
  dotted_border: ^2.0.0+3

  http: ^0.13.6
  share_plus: ^7.2.1

dependency_overrides:
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/png/logo.png
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/images/animations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_assets:
  assets_path: assets/
  output_path: lib/generated/assets/
  filename: assets.dart
flutter_intl:
  enabled: true
