// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL8QJd5SQtmXXoxbBh1MrNw9ytEI-q0zs',
    appId: '1:153049795520:web:5c7b70e05dbc071bba5625',
    messagingSenderId: '153049795520',
    projectId: 'guard-master-2e8fe',
    authDomain: 'guard-master-2e8fe.firebaseapp.com',
    storageBucket: 'guard-master-2e8fe.appspot.com',
    measurementId: 'G-JBFEBMSWB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlO83HSE2DAlbcyPFxcagGT2ypGyG49dA',
    appId: '1:153049795520:android:c9847c3988c01052ba5625',
    messagingSenderId: '153049795520',
    projectId: 'guard-master-2e8fe',
    storageBucket: 'guard-master-2e8fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGOF7aOxAj27H7bvzYzxZ6qTlZhXzVmBw',
    appId: '1:153049795520:ios:46341021d5658de2ba5625',
    messagingSenderId: '153049795520',
    projectId: 'guard-master-2e8fe',
    storageBucket: 'guard-master-2e8fe.appspot.com',
    iosClientId: '153049795520-9p0n2pl4g24kl0m2qdf8ucv1if5d9rtj.apps.googleusercontent.com',
    iosBundleId: 'com.coder.guardmaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGOF7aOxAj27H7bvzYzxZ6qTlZhXzVmBw',
    appId: '1:153049795520:ios:64e7eb6d486ba873ba5625',
    messagingSenderId: '153049795520',
    projectId: 'guard-master-2e8fe',
    storageBucket: 'guard-master-2e8fe.appspot.com',
    iosClientId: '153049795520-7cl0v2jr5bv6a9hcv8j9cj3snk3u79v0.apps.googleusercontent.com',
    iosBundleId: 'com.coder.guardmaster.RunnerTests',
  );
}
